*
* $Id: basic.inc,v 1.1.1.1 1996/02/15 17:48:31 mclareni Exp $
*
* $Log: basic.inc,v $
* Revision 1.1.1.1  1996/02/15 17:48:31  mclareni
* Kernlib
*
*
#ifndef CERNLIB_KERNNUM_BASIC_INC
#define CERNLIB_KERNNUM_BASIC_INC
*
*
* basic.inc
*
           ICTL      2,79
#include "kernnum/setype.inc"
#include "kernnum/link.inc"
#include "kernnum/stack.inc"
#include "kernnum/loop1.inc"
#include "kernnum/loop2.inc"
#include "kernnum/register.inc"

#endif
