*
* $Id: izml3.F,v 1.1.1.1 1996/02/14 13:11:11 mclareni Exp $
*
* $Log: izml3.F,v $
* Revision 1.1.1.1  1996/02/14 13:11:11  mclareni
* Higz
*
*
#include "higz/pilot.h"
#if defined(CERNLIB_ZEBRA)
*CMZ :  1.06/03 09/12/88  10.34.13  by  O.Couet
*-- Author :
      SUBROUTINE IZML3(N,X,Y,Z)
*.===========>
*.
*..==========> (O.Couet)
      DIMENSION X(*),Y(*),Z(*)
*.______________________________________
*
      END
#endif
