#!/usr/bin/perl
if (defined $ENV{'CERN_DEBUG'})
{
	@filtered = grep(!/\-O*/, @filtered);
	push(@filtered, "-g");
	push(@filtered, "-O0");
}
my($cmd) = "gcc @filtered";
print "$cmd\n";
exit(system($cmd));
