*
* $Id: cdunit.inc,v 1.1.1.1 1996/02/28 16:24:02 mclareni Exp $
*
* $Log: cdunit.inc,v $
* Revision 1.1.1.1  1996/02/28 16:24:02  mclareni
* Hepdb, cdlib, etc
*
*
#ifndef CERNLIB_HEPDB_CDUNIT_INC
#define CERNLIB_HEPDB_CDUNIT_INC
*
*
* cdunit.inc
*
*
*     Units for output, errors, redirected output, loglevel
*
      COMMON/CDUNIT/LOUTCD,LPRTCD,LFILCD,LLOGCD
      INTEGER       LOUTCD,LPRTCD,LFILCD,LLOGCD

#endif
