*
* $Id: ctpath.inc,v 1.1.1.1 1996/02/28 16:24:05 mclareni Exp $
*
* $Log: ctpath.inc,v $
* Revision 1.1.1.1  1996/02/28 16:24:05  mclareni
* Hepdb, cdlib, etc
*
*
#ifndef CERNLIB_HEPDB_CTPATH_INC
#define CERNLIB_HEPDB_CTPATH_INC
*
*
* ctpath.inc
*
      COMMON /CTPATH/ PAT1CT, PAT2CT, PAT3CT, PAT4CT, TOP1CT, TOP2CT
      CHARACTER*80    PAT1CT, PAT2CT, PAT3CT, PAT4CT
      CHARACTER*16    TOP1CT, TOP2CT
*

#endif
