*
* $Id: hcfit6.inc,v 1.1.1.1 1996/01/16 17:07:52 mclareni Exp $
*
* $Log: hcfit6.inc,v $
* Revision 1.1.1.1  1996/01/16 17:07:52  mclareni
* First import
*
*
#ifndef CERNLIB_HBOOK_HCFIT6_INC
#define CERNLIB_HBOOK_HCFIT6_INC
*
*
* hcfit6.inc
*
*CMZ :  4.19/00 13/04/93  16.36.40  by  Rene Brun
*-- Author :
      COMMON /HCFIT6/XVAR(10),EPSIF,NUP,NFCNMH,ITPR,IHIS,IMINU,
     +        NX,NY,NPFIT,ILICO,CHIM,IOFSET,IMAT,IBQ(14),ILXE,ILYE,
     +        ILEY,ICSTAT,NFLRET,IDESUM
*

#endif
