*
* $Id: hcpar2.inc,v 1.1.1.1 1996/01/16 17:07:51 mclareni Exp $
*
* $Log: hcpar2.inc,v $
* Revision 1.1.1.1  1996/01/16 17:07:51  mclareni
* First import
*
*
#ifndef CERNLIB_HBOOK_HCPAR2_INC
#define CERNLIB_HBOOK_HCPAR2_INC
*
*
* hcpar2.inc
*
*CMZ :  4.19/00 13/04/93  16.36.40  by  Rene Brun
*-- Author :
      COMMON /HCPAR2/ COEFF(50),IBASFT(10,50),XMIN(10),XMAX(10),
     +                ALIM(10),BLIM(10)
*

#endif
