*
* $Id: hpl9.inc,v 1.1.1.1 1996/01/19 10:50:15 mclareni Exp $
*
* $Log: hpl9.inc,v $
* Revision 1.1.1.1  1996/01/19 10:50:15  mclareni
* Hplot
*
*
#ifndef CERNLIB_HPLOT_HPL9_INC
#define CERNLIB_HPLOT_HPL9_INC
*
*
* hpl9.inc
*
*CMZ :          09/11/95  17.18.57  by  O.Couet
*-- Author :
      COMMON/HPL9/FACTOR,XXSIZE,XX0   ,ICMAX ,ICMAY ,NCMIN, NCMAX
     +    ,YMINI ,YMAXI ,XMINI ,XMAXI
     +    ,YWMINI ,YWMAXI ,XWMINI ,XWMAXI
     +    ,RDIVX ,RDIVY ,RDIVZ
     +    ,IHSLY1,IHSLY2,IHSLY3,IHSLY4

#endif
