*
* $Id: testee.inc,v 1.1.1.1 1996/03/06 10:47:03 mclareni Exp $
*
* $Log: testee.inc,v $
* Revision 1.1.1.1  1996/03/06 10:47:03  mclareni
* Zebra
*
*
*
* testee.inc
*
                       DIMENSION    LV(27),LAV(6),LBV(4),LCV(4)
                       DIMENSION    LLV(6),LXV(6)
                       EQUIVALENCE (LV(1), LA1), (LAV(1),LA1)
                       EQUIVALENCE (LBV(1),LB1), (LCV(1),LC1)
                       EQUIVALENCE (LLV(1),LL1), (LXV(1),LX1)
