*
* $Id: famucm.inc,v 1.1.1.1 1996/03/07 15:17:54 mclareni Exp $
*
* $Log: famucm.inc,v $
* Revision 1.1.1.1  1996/03/07 15:17:54  mclareni
* Fatmen
*
*
#ifndef CERNLIB_FATMEN_FAMUCM_INC
#define CERNLIB_FATMEN_FAMUCM_INC
*
* For FMMODU
*
* famucm.inc
*
      COMMON/FAMUCM/IOPT,IWORDS(10),CHUCOM,CHUFRM,CHFILE
      CHARACTER*80 CHUCOM
      CHARACTER*4  CHUFRM
      CHARACTER*20 CHFILE
#include "fatmen/fatoptd.inc"

#endif
