CDECK  ID>, INISEQ.
      SUBROUTINE INISEQ

C-    Initialize the built-in sequences
C.    started 12-jan-94

      PARAMETER (KM1=1,KM2=2,KM3=4,KM4=8,KM5=16,KM6=32,KM7=64,KM8=128,
     +  KM9=256, KM10=512, KM11=1024, KM12=2048, KM13=4096, KM14=8192,
     +  KM15=16384, KM16=32768, KM17=65536, KM18=131072, KM19=262144)
      CHARACTER      CQBLAN*128, CQEQS*128, CQCETA*32
      CHARACTER      CQAPO*1, CQBSL*1, CQTAB*1
      COMMON /QCHAR/ CQBLAN, CQEQS, CQCETA, CQAPO, CQBSL, CQTAB
      CHARACTER      CQDATEM*10, CQDATE*8, CQTIME*5
      COMMON /QSTATE/NQERR,NQWARN,NQINFO,NQLOCK
     +,              IQDATE,IQTIME, CQDATEM,CQDATE,CQTIME
      CHARACTER      CCKORG*256, CCKARD*256, CCCOMF*256
      COMMON /CCPARA/NCHCCD,NCHCCT, JCCTYP,JCCLEV,JCCSL,MCCPAR(240)
     +,              NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWAR,ICCSUB,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
     +,              JCCEND, NCHCCC,IXCCC,  CCKORG, CCKARD, CCCOMF
      PARAMETER     (JSPSEQ1=3, JSPDATE=9, JSPSEQL=15)
      PARAMETER      (NEWLN=10, NCHNEWL=1)
      PARAMETER      (NSIZEQ=100000, NSIZELN=100000)
      PARAMETER      (NSIZETX=40*NSIZELN)
                     CHARACTER    TEXT(NSIZETX)*1
                     DIMENSION    LQ(NSIZEQ), IQ(NSIZEQ), MLIAD(NSIZELN)
                     EQUIVALENCE (LQ,IQ,LQGARB), (MLIAD(1),LQ(NSIZEQ))
                     EQUIVALENCE (TEXT(1), MLIAD(NSIZELN))
      COMMON //      IQUEST(100),LQGARB,LQHOLD,LQARRV,LQKEEP,LQPREP
C--------------    End CDE              --------------------------------


      CCKARD = ' '
      CCKARD(1:1) = CQBSL
      CCKARD(2:2) = CQBSL
      N = LNBLNK (CCKARD(1:8))
      JSLH = LN_TO4 (CCKARD,N)

      CCKARD(1:20) = '      IDATQQ= 00    '
C-                    _:.=+=.:_1_:.=+=.:_2
      CALL CSETDI (IQDATE,CCKARD,15,20)
      JSLD = LN_TO4 (CCKARD,20)

      CCKARD(1:18) = '      ITIMQQ=     '
C-                    _:.=+=.:_1_:.=+=.:_2
      CALL CSETDI (IQTIME,CCKARD,15,18)
      JSLT = LN_TO4 (CCKARD,18)

      CALL INISQX ('QTERMHD', 0, JSLH, KM5+KM6)
      CALL INISQX ('DATEQQ',  0, JSLD, KM5+KM6)
      CALL INISQX ('TIMEQQ',  0, JSLT, KM5+KM6)

      MASK = KM13+KM5+KM6
      DO 64 IX=JSPSEQ1,JSPSEQL
   64 CALL INISQX (' ', IX, 1, MASK)
      RETURN

      END
