CDECK  ID>, MK_FNX.
      SUBROUTINE MK_FNX

C-    Step to next PREP / MAT bank for DOFORG
C.    started  1-dec-91

      PARAMETER (KM1=1,KM2=2,KM3=4,KM4=8,KM5=16,KM6=32,KM7=64,KM8=128,
     +  KM9=256, KM10=512, KM11=1024, KM12=2048, KM13=4096, KM14=8192,
     +  KM15=16384, KM16=32768, KM17=65536, KM18=131072, KM19=262144)
      PARAMETER  (MCCNIL=1,  MCCKIL=2,  MCCINC=3,  MCCCDE=4,  MCCSEQ=5,
     + MCCXSQ=6,  MCCTRU=7,  MCCFAL=8,  MCCELS=9,  MCCEND=10,
     +            MCCSEL=11, MCCSES=12, MCCFAU=13, MCCSKI=14,
     +            MCCKEE=15, MCCDEL=16, MCCREP=17, MCCADB=18, MCCADD=19,
     + MCCUSE=20, MCCXDI=21, MCCDIV=22, MCCLIS=23, MCCEXE=24, MCCIMI=25,
     + MCCASM=26, MCCUPD=27, MCCNAM=28, MCCGAP=29, MCCMOR=30, MCCONL=31,
     + MCCFOR=32, MCCSUS=33, MCCOPT=34, MCCOP2=35, MCCSHO=36, MCCPAM=37,
     + MCCQUI=38, MCCEOD=39, MCCDEC=40, MCCPAT=41, MCCTIT=42)
      CHARACTER      CCKORG*256, CCKARD*256, CCCOMF*256
      COMMON /CCPARA/NCHCCD,NCHCCT, JCCTYP,JCCLEV,JCCSL,MCCPAR(240)
     +,              NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWAR,ICCSUB,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
     +,              JCCEND, NCHCCC,IXCCC,  CCKORG, CCKARD, CCCOMF
      PARAMETER      (NEWLN=10, NCHNEWL=1)
      PARAMETER      (NSIZEQ=100000, NSIZELN=100000)
      PARAMETER      (NSIZETX=40*NSIZELN)
                     CHARACTER    TEXT(NSIZETX)*1
                     DIMENSION    LQ(NSIZEQ), IQ(NSIZEQ), MLIAD(NSIZELN)
                     EQUIVALENCE (LQ,IQ,LQGARB), (MLIAD(1),LQ(NSIZEQ))
                     EQUIVALENCE (TEXT(1), MLIAD(NSIZELN))
      COMMON //      IQUEST(100),LQGARB,LQHOLD,LQARRV,LQKEEP,LQPREP
      COMMON /MUSEBC/ MX_FORC, MU_GLOB, MU_PAT, MU_DECK, MU_INH, MU_FORG
     +,               MX_TRAN, MX_FORG, MX_SINH, MX_SELF, NVEXDK(6)
      COMMON /M_ANAC/LOWAN,KDOAN,LDOAN,LUPAN,MODEAN,MEXAN,LEVAN,KKM5AN
     +,              NEWDEC,NEWCTL,NEWFOR,NEWNIL,NEWINC
C--------------    End CDE              --------------------------------

      IAND (IZV,IZW) = AND (IZV, IZW)
      IOR  (IZV,IZW) =  OR (IZV, IZW)


      MEXSUS = 0
      IFLNEW = 0
   21 IF (LUPAN.NE.0)              GO TO 34
   22 KDOAN = LDOAN - 1
      LDOAN = LQ(KDOAN)
      IF (LDOAN.EQ.0)              GO TO 29

      L = LQ(LDOAN-2)
      IF (L.NE.0)                  GO TO 31

   24 JCCTYP = JBYT (IQ(LDOAN),9,6)
      IF (IAND(IQ(LDOAN),KM5+KM6).EQ.0)  GO TO 28

C--       deleted PREP/MAT bank

      IF (JCCTYP.GE.MCCSEL)  THEN
          IFLNEW= 7
          IF (IAND(IQ(LDOAN),KM6+KM7).EQ.0)  GO TO 29
        ENDIF

      IF (IFLNEW.NE.0)  THEN
          MEXSUS = IOR (MEXSUS, IQ(LDOAN))
        ELSE
          MEXAN = IOR (MEXAN, IQ(LDOAN))
        ENDIF
      GO TO 21

C--       accepted PREP/MAT bank

   28 IF (JCCTYP.LT.MCCSEL)  THEN
          IF (NVEXDK(2).NE.0)  CALL DPLIST (MODEAN,LDOAN,LUPAN,0)
          MEXAN = IOR (MEXAN, IQ(LDOAN))
          MEXAN = IOR (MEXAN, MEXSUS)
        ENDIF

   29 MEXAN = IAND (MEXAN,15)
      RETURN

C----              Follow reference to foreign material

   31 LOWAN = LDOAN
      LUPAN = L

C--       list what action

      CALL DPLACT
      IF (IAND(IQ(LOWAN),KM5+KM6).NE.0)  GO TO 37

C--       next MAT bank

      LDOAN = LUPAN - 1
   34 KDOAN = LDOAN - 1
      LDOAN = LQ(KDOAN)
      IF (LDOAN.NE.0)              GO TO 24
   36 LDOAN  = LOWAN
      LUPAN  = 0
      GO TO 22

   37 MEXSUS = IOR (MEXSUS, IQ(LOWAN))
      MEXSUS = IOR (MEXSUS, IQ(LUPAN))
      GO TO 36
      END
