CDECK  ID>, SYSPLIT.
      SUBROUTINE SYSPLIT (LTHIS)

C-    split on +CDE or +SEQ contained in a sequence definition
C.    started 24-aug-95

      PARAMETER  (MCCNIL=1,  MCCKIL=2,  MCCINC=3,  MCCCDE=4,  MCCSEQ=5,
     + MCCXSQ=6,  MCCTRU=7,  MCCFAL=8,  MCCELS=9,  MCCEND=10,
     +            MCCSEL=11, MCCSES=12, MCCFAU=13, MCCSKI=14,
     +            MCCKEE=15, MCCDEL=16, MCCREP=17, MCCADB=18, MCCADD=19,
     + MCCUSE=20, MCCXDI=21, MCCDIV=22, MCCLIS=23, MCCEXE=24, MCCIMI=25,
     + MCCASM=26, MCCUPD=27, MCCNAM=28, MCCGAP=29, MCCMOR=30, MCCONL=31,
     + MCCFOR=32, MCCSUS=33, MCCOPT=34, MCCOP2=35, MCCSHO=36, MCCPAM=37,
     + MCCQUI=38, MCCEOD=39, MCCDEC=40, MCCPAT=41, MCCTIT=42)
      CHARACTER      CCKORG*256, CCKARD*256, CCCOMF*256
      COMMON /CCPARA/NCHCCD,NCHCCT, JCCTYP,JCCLEV,JCCSL,MCCPAR(240)
     +,              NCCPAR,MXCCIF,JCCIFV,JCCBAD,JCCWAR,ICCSUB,JCCWK(4)
     +,              JCCPP,JCCPD,JCCPZ,JCCPT,JCCPIF,JCCPC,JCCPN
     +,              NCCPP,NCCPD,NCCPZ,NCCPT,NCCPIF,NCCPC,NCCPN
     +,              JCCEND, NCHCCC,IXCCC,  CCKORG, CCKARD, CCCOMF
      PARAMETER      (NEWLN=10, NCHNEWL=1)
      PARAMETER      (NSIZEQ=100000, NSIZELN=100000)
      PARAMETER      (NSIZETX=40*NSIZELN)
                     CHARACTER    TEXT(NSIZETX)*1
                     DIMENSION    LQ(NSIZEQ), IQ(NSIZEQ), MLIAD(NSIZELN)
                     EQUIVALENCE (LQ,IQ,LQGARB), (MLIAD(1),LQ(NSIZEQ))
                     EQUIVALENCE (TEXT(1), MLIAD(NSIZELN))
      COMMON //      IQUEST(100),LQGARB,LQHOLD,LQARRV,LQKEEP,LQPREP
     +,         LEXP,LLPAST,LQPAST, LQUSER(4), LHASM,LRPAM,LPAM, LQINCL
     +,         LACRAD,LARRV, LPCRA,LDCRAB, LEXD,LDECO, LCRP,LCRD, LSERV
     +, INCRAD, IFLGAR, JANSW, IFMODIF, IFALTN
     +, JDKNEX,JDKTYP, JSLZER,NSLORG,JSLORG
     +, MOPTIO(34), MOPUPD, NCLASH, IFLMERG,IFLDISP, NSLFRE,NTXFRE
     +, NVGAP(4), NVGARB(6), NVIMAT(4), NVUTY(4),  LASTWK
C--------------    End CDE              --------------------------------

      IOR  (IZV,IZW) =  OR (IZV, IZW)
      ISHFTL (IZW,NZB) = LSHIFT (IZW, NZB)


      LDO  = LTHIS
      JSLA = IQ(LDO+1)
      JSLE = JSLA + IQ(LDO+2)
      JSLF = JSLA

C----         Find next control line

   20 JSLG = JSLF + 1
   21 IF (JSLG.GE.JSLE)            GO TO 41
      CALL NEXTCC ('+',JSLG,JSLE,JSLF,JTYPE)
      IF (JTYPE.EQ.0)              GO TO 41

      IF (JTYPE.LT.MCCCDE)         GO TO 20
      IF (JTYPE.GT.MCCSEQ)         GO TO 20

C--       split before +CDE

      IF (JSLF.GT.JSLA)  LDO= M_SPLIT (LDO,JSLF)

      IQ(LDO) = IOR (IQ(LDO), ISHFTL(JTYPE,8))
      JSLG = IQ(LDO+1) + 1
      IF (JSLG.GE.JSLE)            GO TO 41

C--       split after +CDE

      LDO  = M_SPLIT (LDO,JSLG)
      JSLA = JSLG
      GO TO 21

C----         step to next bank

   41 LDO = LQ(LDO-1)
      IF (LDO.EQ.0)                RETURN
      IF (LQ(LDO-2).NE.0)          GO TO 41
      JTYPE = JBYT (IQ(LDO),9,6)
      IF (JTYPE.GE.MCCSEL)         RETURN
      JSLA = IQ(LDO+1)
      JSLE = JSLA + IQ(LDO+2)
      JSLG = JSLA
      GO TO 21
      END
