.title       CERNLIB format conversion utility
.ident       'VERSION 1.00'
.facility    CERNLIB,1007/prefix=CRN_
.severity    INFORMATION
NEWLIB       <!AS>/fao_count=1
.severity    WARNING
NOFILE       <file !AS not added>/fao_count=1
NOSUCC       <file !AS already encountered>/fao_count=1
PRODV        <no !AS version available for !AS, PRO version used>/fao_count=2
.severity    ERROR
NOLIB        <no library defined>/fao_count=0
.severity    FATAL
TOOMALNM     <too many logical names (!UL) for !AS>/fao_count=2
.end
