*
* $Id: m429btpw.inc,v 1.1.1.1 1996/02/15 17:47:48 mclareni Exp $
*
* $Log: m429btpw.inc,v $
* Revision 1.1.1.1  1996/02/15 17:47:48  mclareni
* Kernlib
*
*
#ifndef CERNLIB_KERNBIT_M429BTPW_INC
#define CERNLIB_KERNBIT_M429BTPW_INC
*
*
* m429btpw.inc
*
#if defined(CERNLIB_DOUBLE)
C--     DEFAULT FORTRAN VALUE OF NBITPW= 32 BITS PER WORD
C--     NBITPW FOR IBM,VAX OR NORD ( 32 BITS PER WORD)
      PARAMETER( NBITPW=32 )
#endif

#endif
