*
* $Id: qversion.inc,v 1.4 2003/08/15 15:19:12 mclareni Exp $
*
* $Log: qversion.inc,v $
* Revision 1.4  2003/08/15 15:19:12  mclareni
* Version 3.79
*
* Revision 1.3  1999/06/18 12:04:48  couet
* - The version is now defined in one central place
*
* Revision 1.2  1996/04/18 16:15:27  mclareni
* Incorporate changes from J.Zoll for version 3.77
*
* Revision 1.1.1.1  1996/03/06 10:46:55  mclareni
* Zebra
*
*
#ifndef CERNLIB_ZEBRA_QVERSION_INC
#define CERNLIB_ZEBRA_QVERSION_INC
*
*    Version number
*
      QVERSN = 3.79
#endif
