*
* $Id: hi3d.inc,v 1.1.1.1 1996/02/14 13:10:13 mclareni Exp $
*
* $Log: hi3d.inc,v $
* Revision 1.1.1.1  1996/02/14 13:10:13  mclareni
* Higz
*
*
#ifndef CERNLIB_HIGZ_HI3D_INC
#define CERNLIB_HIGZ_HI3D_INC
*
*
* hi3d.inc
*
*CMZ :  1.23/06 14/11/95  10.18.18  by  O.Couet
*-- Author :    O.Couet   20/12/93
      COMMON /HI3D/ AWNX,BWNX,CWNX,DWNX,
     +              AWNY,BWNY,CWNY,DWNY,
     +              AWNZ,BWNZ,CWNZ,DWNZ

#endif
