*
* $Id:
*
* $Log:
*
#ifndef CERNLIB_HIGZ_HILINK_INC
#define CERNLIB_HIGZ_HILINK_INC
*
*
* hilink.inc
*
*-- Author : O.Couet
      COMMON /HILINK/ LHIGZ,LCG,LWV
     +,               LPICT,LHNT0,LHI,LHF,LHC,LHNT,LHNTLA
     +,               LPICD,LDNT0,LDI,LDF,LDC,LDNT,LDNTLA
     +,               LPIC2,L2NT0,L2I,L2F,L2C,L2NT,L2NTLA
     +,               LNDECO,LIDECO,LFDECO,LCDECO
     +,               LPSAV,LPCOP,LNTCOP,LSTACK(10),LAST
#endif
