*
* $Id: numcdopt.h,v 1.1.1.1 1996/02/15 17:47:58 mclareni Exp $
*
* $Log: numcdopt.h,v $
* Revision 1.1.1.1  1996/02/15 17:47:58  mclareni
* Kernlib
*
*
* This directory was created from kernnum.car patch numcdopt
#ifndef CERNLIB_KERNCD
#define CERNLIB_KERNCD
#endif
#ifndef CERNLIB_E208CD
#define CERNLIB_E208CD
#endif
#ifndef CERNLIB_F002CD
#define CERNLIB_F002CD
#endif
#ifndef CERNLIB_F003CD
#define CERNLIB_F003CD
#endif
#ifndef CERNLIB_F004CD
#define CERNLIB_F004CD
#endif
#ifndef CERNLIB_F011CD
#define CERNLIB_F011CD
#endif
#ifndef CERNLIB_F012CD
#define CERNLIB_F012CD
#endif
#ifndef CERNLIB_G900CD
#define CERNLIB_G900CD
#endif
#ifndef CERNLIB_E208FORT_E208PR
#define CERNLIB_E208FORT_E208PR
#endif
#ifndef CERNLIB_F002FORT_DVADD
#define CERNLIB_F002FORT_DVADD
#endif
#ifndef CERNLIB_F002FORT_CVADD
#define CERNLIB_F002FORT_CVADD
#endif
#ifndef CERNLIB_F002FORT_DVDIV
#define CERNLIB_F002FORT_DVDIV
#endif
#ifndef CERNLIB_F002FORT_CVDIV
#define CERNLIB_F002FORT_CVDIV
#endif
#ifndef CERNLIB_F002FORT_CVMPAC
#define CERNLIB_F002FORT_CVMPAC
#endif
#ifndef CERNLIB_F002FORT_CVMPYC
#define CERNLIB_F002FORT_CVMPYC
#endif
#ifndef CERNLIB_F002FORT_DVMUL
#define CERNLIB_F002FORT_DVMUL
#endif
#ifndef CERNLIB_F002FORT_DVMULA
#define CERNLIB_F002FORT_DVMULA
#endif
#ifndef CERNLIB_F002FORT_DVMUNA
#define CERNLIB_F002FORT_DVMUNA
#endif
#ifndef CERNLIB_F002FORT_DVRAN
#define CERNLIB_F002FORT_DVRAN
#endif
#ifndef CERNLIB_F002FORT_CVRAN
#define CERNLIB_F002FORT_CVRAN
#endif
#ifndef CERNLIB_F002FORT_DVSET
#define CERNLIB_F002FORT_DVSET
#endif
#ifndef CERNLIB_F002FORT_CVSET
#define CERNLIB_F002FORT_CVSET
#endif
#ifndef CERNLIB_F002FORT_DVSUB
#define CERNLIB_F002FORT_DVSUB
#endif
#ifndef CERNLIB_F002FORT_CVSUB
#define CERNLIB_F002FORT_CVSUB
#endif
#ifndef CERNLIB_F002FORT_DVSUM
#define CERNLIB_F002FORT_DVSUM
#endif
#ifndef CERNLIB_F002FORT_CVSUM
#define CERNLIB_F002FORT_CVSUM
#endif
#ifndef CERNLIB_F003FORT_CMMPYC
#define CERNLIB_F003FORT_CMMPYC
#endif
#ifndef CERNLIB_F003FORT_CCMMPY
#define CERNLIB_F003FORT_CCMMPY
#endif
#ifndef CERNLIB_F003FORT_CUMPYC
#define CERNLIB_F003FORT_CUMPYC
#endif
#ifndef CERNLIB_F003FORT_CCUMPY
#define CERNLIB_F003FORT_CCUMPY
#endif
#ifndef CERNLIB_F003FORT_DMBIL
#define CERNLIB_F003FORT_DMBIL
#endif
#ifndef CERNLIB_F003FORT_CMBIL
#define CERNLIB_F003FORT_CMBIL
#endif
#ifndef CERNLIB_F003FORT_DMRAN
#define CERNLIB_F003FORT_DMRAN
#endif
#ifndef CERNLIB_F003FORT_CMRAN
#define CERNLIB_F003FORT_CMRAN
#endif
#ifndef CERNLIB_F003FORT_DMSCL
#define CERNLIB_F003FORT_DMSCL
#endif
#ifndef CERNLIB_F003FORT_CMSCL
#define CERNLIB_F003FORT_CMSCL
#endif
#ifndef CERNLIB_F003FORT_DMSET
#define CERNLIB_F003FORT_DMSET
#endif
#ifndef CERNLIB_F003FORT_CMSET
#define CERNLIB_F003FORT_CMSET
#endif
#ifndef CERNLIB_F004FORT_CMMLTC
#define CERNLIB_F004FORT_CMMLTC
#endif
#ifndef CERNLIB_F011FORT_TMPRNT
#define CERNLIB_F011FORT_TMPRNT
#endif
