PROTOCCALLSFSUB1(IACWK,iacwk,INT)
#define IACWK(A1)  CCALLSFSUB1(IACWK,iacwk,INT,A1)

PROTOCCALLSFSUB8(ICA,ica,FLOAT,FLOAT,FLOAT,FLOAT,INT,INT,PINT,STRING)
#define ICA(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(ICA,ica,FLOAT,FLOAT,FLOAT,FLOAT,INT,INT,PINT,STRING,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB0(ICLKS,iclks)
#define ICLKS() CCALLSFSUB0(ICLKS,iclks)

PROTOCCALLSFSUB2(ICLRWK,iclrwk,INT,INT)
#define ICLRWK(A1,A2)  CCALLSFSUB2(ICLRWK,iclrwk,INT,INT,A1,A2)

PROTOCCALLSFSUB1(ICLWK,iclwk,INT)
#define ICLWK(A1)  CCALLSFSUB1(ICLWK,iclwk,INT,A1)

PROTOCCALLSFSUB1(IDAWK,idawk,INT)
#define IDAWK(A1)  CCALLSFSUB1(IDAWK,idawk,INT,A1)

PROTOCCALLSFSUB3(IFA,ifa,INT,FLOATV,FLOATV)
#define IFA(A1,A2,A3)  CCALLSFSUB3(IFA,ifa,INT,FLOATV,FLOATV,A1,A2,A3)

PROTOCCALLSFSUB4(IFA3,ifa3,INT,FLOATV,FLOATV,FLOATV)
#define IFA3(A1,A2,A3,A4)  CCALLSFSUB4(IFA3,ifa3,INT,FLOATV,FLOATV,FLOATV,A1,A2,A3,A4)

PROTOCCALLSFSUB6(IGARC,igarc,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT)
#define IGARC(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IGARC,igarc,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB8(IGAXIS,igaxis,FLOAT,FLOAT,FLOAT,FLOAT,PFLOAT,PFLOAT,PINT,STRING)
#define IGAXIS(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(IGAXIS,igaxis,FLOAT,FLOAT,FLOAT,FLOAT,PFLOAT,PFLOAT,PINT,STRING,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB4(IGBOX,igbox,FLOAT,FLOAT,FLOAT,FLOAT)
#define IGBOX(A1,A2,A3,A4)  CCALLSFSUB4(IGBOX,igbox,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4)

PROTOCCALLSFSUB9(IGCOLM,igcolm,FLOAT,FLOAT,FLOAT,FLOAT,PINT,INTV,FLOAT,FLOAT,STRING)
#define IGCOLM(A1,A2,A3,A4,A5,A6,A7,A8,A9)  CCALLSFSUB9(IGCOLM,igcolm,FLOAT,FLOAT,FLOAT,FLOAT,PINT,INTV,FLOAT,FLOAT,STRING,A1,A2,A3,A4,A5,A6,A7,A8,A9)

PROTOCCALLSFSUB0(IGEND,igend)
#define IGEND() CCALLSFSUB0(IGEND,igend)

PROTOCCALLSFSUB4(IGHIST,ighist,INT,FLOATV,FLOATV,STRING)
#define IGHIST(A1,A2,A3,A4)  CCALLSFSUB4(IGHIST,ighist,INT,FLOATV,FLOATV,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB1(IGINIT,iginit,INT)
#define IGINIT(A1)  CCALLSFSUB1(IGINIT,iginit,INT,A1)

PROTOCCALLSFSUB2(IGLBL,iglbl,INT,STRINGV)
#define IGLBL(A1,A2)  CCALLSFSUB2(IGLBL,iglbl,INT,STRINGV,A1,A2)

PROTOCCALLSFSUB7(IGLOC,igloc,INT,PINT,PINT,PFLOAT,PFLOAT,PFLOAT,PFLOAT)
#define IGLOC(A1,A2,A3,A4,A5,A6,A7)  CCALLSFSUB7(IGLOC,igloc,INT,PINT,PINT,PFLOAT,PFLOAT,PFLOAT,PFLOAT,A1,A2,A3,A4,A5,A6,A7)

PROTOCCALLSFSUB8(IGLOC2,igloc2,INT,INT,FLOAT,FLOAT,FLOAT,FLOAT,INT,STRING)
#define IGLOC2(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(IGLOC2,igloc2,INT,INT,FLOAT,FLOAT,FLOAT,FLOAT,INT,STRING,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB14(IGMENU,igmenu,INT,STRING,PFLOAT,PFLOAT,PFLOAT,PFLOAT,INT,STRINGV,INT,STRINGV,STRINGV,PSTRINGV,PINT,STRING)
#define IGMENU(A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14)  CCALLSFSUB14(IGMENU,igmenu,INT,STRING,PFLOAT,PFLOAT,PFLOAT,PFLOAT,INT,STRINGV,INT,STRINGV,STRINGV,PSTRINGV,PINT,STRING,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10,A11,A12,A13,A14)

PROTOCCALLSFSUB4(IGMESS,igmess,INT,STRINGV,STRING,STRING)
#define IGMESS(A1,A2,A3,A4)  CCALLSFSUB4(IGMESS,igmess,INT,STRINGV,STRING,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB2(IGMETA,igmeta,INT,INT)
#define IGMETA(A1,A2)  CCALLSFSUB2(IGMETA,igmeta,INT,INT,A1,A2)

PROTOCCALLSFSUB8(IGPAVE,igpave,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,INT,INT,STRING)
#define IGPAVE(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(IGPAVE,igpave,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,INT,INT,STRING,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB7(IGPICK,igpick,INT,FLOAT,FLOAT,PINT,PSTRINGV,PINT,STRING)
#define IGPICK(A1,A2,A3,A4,A5,A6,A7)  CCALLSFSUB7(IGPICK,igpick,INT,FLOAT,FLOAT,PINT,PSTRINGV,PINT,STRING,A1,A2,A3,A4,A5,A6,A7)

PROTOCCALLSFSUB4(IGPID,igpid,INT,STRING,INT,STRING)
#define IGPID(A1,A2,A3,A4)  CCALLSFSUB4(IGPID,igpid,INT,STRING,INT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB9(IGPIE,igpie,FLOAT,FLOAT,FLOAT,INT,FLOATV,STRING,INTV,INTV,INTV)
#define IGPIE(A1,A2,A3,A4,A5,A6,A7,A8,A9)  CCALLSFSUB9(IGPIE,igpie,FLOAT,FLOAT,FLOAT,INT,FLOATV,STRING,INTV,INTV,INTV,A1,A2,A3,A4,A5,A6,A7,A8,A9)

PROTOCCALLSFSUB2(IGQ,igq,STRING,PFLOAT)
#define IGQ(A1,A2)  CCALLSFSUB2(IGQ,igq,STRING,PFLOAT,A1,A2)

PROTOCCALLSFSUB3(IGQWK,igqwk,INT,STRING,FLOATV)
#define IGQWK(A1,A2,A3)  CCALLSFSUB3(IGQWK,igqwk,INT,STRING,FLOATV,A1,A2,A3)

PROTOCCALLSFSUB4(IGRAPH,igraph,INT,FLOATV,FLOATV,STRING)
#define IGRAPH(A1,A2,A3,A4)  CCALLSFSUB4(IGRAPH,igraph,INT,FLOATV,FLOATV,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB2(IGRNG,igrng,FLOAT,FLOAT)
#define IGRNG(A1,A2)  CCALLSFSUB2(IGRNG,igrng,FLOAT,FLOAT,A1,A2)

PROTOCCALLSFSUB1(IGRSIZ,igrsiz,INT)
#define IGRSIZ(A1)  CCALLSFSUB1(IGRSIZ,igrsiz,INT,A1)

PROTOCCALLSFSUB6(IGRTOH,igrtoh,FLOAT,FLOAT,FLOAT,PFLOAT,PFLOAT,PFLOAT)
#define IGRTOH(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IGRTOH,igrtoh,FLOAT,FLOAT,FLOAT,PFLOAT,PFLOAT,PFLOAT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB6(IGHTOR,ightor,FLOAT,FLOAT,FLOAT,PFLOAT,PFLOAT,PFLOAT)
#define IGHTOR(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IGHTOR,ightor,FLOAT,FLOAT,FLOAT,PFLOAT,PFLOAT,PFLOAT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB1(IGSA,igsa,INT)
#define IGSA(A1)  CCALLSFSUB1(IGSA,igsa,INT,A1)

PROTOCCALLSFSUB2(IGSET,igset,STRING,FLOAT)
#define IGSET(A1,A2)  CCALLSFSUB2(IGSET,igset,STRING,FLOAT,A1,A2)

PROTOCCALLSFSUB1(IGSG,igsg,INT)
#define IGSG(A1)  CCALLSFSUB1(IGSG,igsg,INT,A1)

PROTOCCALLSFSUB2(IGSSE,igsse,INT,INT)
#define IGSSE(A1,A2)  CCALLSFSUB2(IGSSE,igsse,INT,INT,A1,A2)

PROTOCCALLSFSUB6(IGTABL,igtabl,INT,INT,FLOATV,INT,FLOATV,STRING)
#define IGTABL(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IGTABL,igtabl,INT,INT,FLOATV,INT,FLOATV,STRING,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB0(IGTERM,igterm)
#define IGTERM() CCALLSFSUB0(IGTERM,igterm)

PROTOCCALLSFSUB6(IGTEXT,igtext,FLOAT,FLOAT,STRING,FLOAT,PFLOAT,STRING)
#define IGTEXT(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IGTEXT,igtext,FLOAT,FLOAT,STRING,FLOAT,PFLOAT,STRING,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB1(IGWKTY,igwkty,PINT)
#define IGWKTY(A1)  CCALLSFSUB1(IGWKTY,igwkty,PINT,A1)

PROTOCCALLSFSUB7(IGXMES,igxmes,INT,INT,INT,INT,STRINGV,STRING,STRING)
#define IGXMES(A1,A2,A3,A4,A5,A6,A7)  CCALLSFSUB7(IGXMES,igxmes,INT,INT,INT,INT,STRINGV,STRING,STRING,A1,A2,A3,A4,A5,A6,A7)

PROTOCCALLSFSUB1(IGZSET,igzset,STRING)
#define IGZSET(A1)  CCALLSFSUB1(IGZSET,igzset,STRING,A1)

PROTOCCALLSFSUB1(IOPKS,iopks,INT)
#define IOPKS(A1)  CCALLSFSUB1(IOPKS,iopks,INT,A1)

PROTOCCALLSFSUB3(IOPWK,iopwk,INT,INT,INT)
#define IOPWK(A1,A2,A3)  CCALLSFSUB3(IOPWK,iopwk,INT,INT,INT,A1,A2,A3)

PROTOCCALLSFSUB3(IPL,ipl,INT,FLOATV,FLOATV)
#define IPL(A1,A2,A3)  CCALLSFSUB3(IPL,ipl,INT,FLOATV,FLOATV,A1,A2,A3)

PROTOCCALLSFSUB4(IPL3,ipl3,INT,FLOATV,FLOATV,FLOATV)
#define IPL3(A1,A2,A3,A4)  CCALLSFSUB4(IPL3,ipl3,INT,FLOATV,FLOATV,FLOATV,A1,A2,A3,A4)

PROTOCCALLSFSUB3(IPM,ipm,INT,FLOATV,FLOATV)
#define IPM(A1,A2,A3)  CCALLSFSUB3(IPM,ipm,INT,FLOATV,FLOATV,A1,A2,A3)

PROTOCCALLSFSUB4(IPM3,ipm3,INT,FLOATV,FLOATV,FLOATV)
#define IPM3(A1,A2,A3,A4)  CCALLSFSUB4(IPM3,ipm3,INT,FLOATV,FLOATV,FLOATV,A1,A2,A3,A4)

PROTOCCALLSFSUB6(IPM3ID,ipm3id,INT,FLOATV,FLOATV,FLOATV,INT,INTV)
#define IPM3ID(A1,A2,A3,A4,A5,A6) CCALLSFSUB6(IPM3ID,ipm3id,INT,FLOATV,FLOATV,FLOATV,INT,INTV,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB9(IPM4ID,ipm4id,INT,FLOATV,FLOATV,FLOATV,FLOATV,FLOAT,FLOAT,INT,INTV)
#define IPM4ID(A1,A2,A3,A4,A5,A6,A7,A8,A9) CCALLSFSUB9(IPM4ID,ipm4id,INT,FLOATV,FLOATV,FLOATV,FLOATV,FLOAT,FLOAT,INT,INTV,A1,A2,A3,A4,A5,A6,A7,A8,A9)

PROTOCCALLSFSUB5(IPMID,ipmid,INT,FLOATV,FLOATV,INT,INTV)
#define IPMID(A1,A2,A3,A4,A5) CCALLSFSUB5(IPMID,ipmid,INT,FLOATV,FLOATV,INT,INTV,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB6(IRQLC,irqlc,INT,INT,INT,INT,FLOAT,FLOAT)
#define IRQLC(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IRQLC,irqlc,INT,INT,INT,INT,FLOAT,FLOAT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB5(IRQST,irqst,INT,INT,INT,INT,FLOAT)
#define IRQST(A1,A2,A3,A4,A5)  CCALLSFSUB5(IRQST,irqst,INT,INT,INT,INT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB1(ISCHH,ischh,FLOAT)
#define ISCHH(A1)  CCALLSFSUB1(ISCHH,ischh,FLOAT,A1)

PROTOCCALLSFSUB2(ISCHUP,ischup,FLOAT,FLOAT)
#define ISCHUP(A1,A2)  CCALLSFSUB2(ISCHUP,ischup,FLOAT,FLOAT,A1,A2)

PROTOCCALLSFSUB1(ISCLIP,isclip,INT)
#define ISCLIP(A1)  CCALLSFSUB1(ISCLIP,isclip,INT,A1)

PROTOCCALLSFSUB5(ISCR,iscr,INT,INT,FLOAT,FLOAT,FLOAT)
#define ISCR(A1,A2,A3,A4,A5)  CCALLSFSUB5(ISCR,iscr,INT,INT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB1(ISELNT,iselnt,INT)
#define ISELNT(A1)  CCALLSFSUB1(ISELNT,iselnt,INT,A1)

PROTOCCALLSFSUB1(ISFACI,isfaci,INT)
#define ISFACI(A1)  CCALLSFSUB1(ISFACI,isfaci,INT,A1)

PROTOCCALLSFSUB1(ISFAIS,isfais,INT)
#define ISFAIS(A1)  CCALLSFSUB1(ISFAIS,isfais,INT,A1)

PROTOCCALLSFSUB1(ISFASI,isfasi,INT)
#define ISFASI(A1)  CCALLSFSUB1(ISFASI,isfasi,INT,A1)

PROTOCCALLSFSUB1(ISLN,isln,INT)
#define ISLN(A1)  CCALLSFSUB1(ISLN,isln,INT,A1)

PROTOCCALLSFSUB1(ISLWSC,islwsc,FLOAT)
#define ISLWSC(A1)  CCALLSFSUB1(ISLWSC,islwsc,FLOAT,A1)

PROTOCCALLSFSUB1(ISMK,ismk,INT)
#define ISMK(A1)  CCALLSFSUB1(ISMK,ismk,INT,A1)

PROTOCCALLSFSUB1(ISMKSC,ismksc,FLOAT)
#define ISMKSC(A1)  CCALLSFSUB1(ISMKSC,ismksc,FLOAT,A1)

PROTOCCALLSFSUB1(ISPLCI,isplci,INT)
#define ISPLCI(A1)  CCALLSFSUB1(ISPLCI,isplci,INT,A1)

PROTOCCALLSFSUB1(ISPMCI,ispmci,INT)
#define ISPMCI(A1)  CCALLSFSUB1(ISPMCI,ispmci,INT,A1)

PROTOCCALLSFSUB2(ISTXAL,istxal,INT,INT)
#define ISTXAL(A1,A2)  CCALLSFSUB2(ISTXAL,istxal,INT,INT,A1,A2)

PROTOCCALLSFSUB1(ISTXCI,istxci,INT)
#define ISTXCI(A1)  CCALLSFSUB1(ISTXCI,istxci,INT,A1)

PROTOCCALLSFSUB2(ISTXFP,istxfp,INT,INT)
#define ISTXFP(A1,A2)  CCALLSFSUB2(ISTXFP,istxfp,INT,INT,A1,A2)

PROTOCCALLSFSUB5(ISVP,isvp,INT,FLOAT,FLOAT,FLOAT,FLOAT)
#define ISVP(A1,A2,A3,A4,A5)  CCALLSFSUB5(ISVP,isvp,INT,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB5(ISWKVP,iswkvp,INT,FLOAT,FLOAT,FLOAT,FLOAT)
#define ISWKVP(A1,A2,A3,A4,A5)  CCALLSFSUB5(ISWKVP,iswkvp,INT,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB5(ISWKWN,iswkwn,INT,FLOAT,FLOAT,FLOAT,FLOAT)
#define ISWKWN(A1,A2,A3,A4,A5)  CCALLSFSUB5(ISWKWN,iswkwn,INT,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB5(ISWN,iswn,INT,FLOAT,FLOAT,FLOAT,FLOAT)
#define ISWN(A1,A2,A3,A4,A5)  CCALLSFSUB5(ISWN,iswn,INT,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB3(ITX,itx,FLOAT,FLOAT,STRING)
#define ITX(A1,A2,A3)  CCALLSFSUB3(ITX,itx,FLOAT,FLOAT,STRING,A1,A2,A3)

PROTOCCALLSFSUB4(ITX3,itx3,FLOAT,FLOAT,FLOAT,STRING)
#define ITX3(A1,A2,A3,A4)  CCALLSFSUB4(ITX3,itx3,FLOAT,FLOAT,FLOAT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB2(IUWK,iuwk,INT,INT)
#define IUWK(A1,A2)  CCALLSFSUB2(IUWK,iuwk,INT,INT,A1,A2)

PROTOCCALLSFSUB2(IZCTOI,izctoi,STRING,INT)
#define IZCTOI(A1,A2)  CCALLSFSUB2(IZCTOI,izctoi,STRING,INT,A1,A2)

PROTOCCALLSFSUB2(IZCTOR,izctor,STRING,PFLOAT)
#define IZCTOR(A1,A2)  CCALLSFSUB2(IZCTOR,izctor,STRING,PFLOAT,A1,A2)

PROTOCCALLSFSUB2(IZITOC,izitoc,INT,STRING)
#define IZITOC(A1,A2)  CCALLSFSUB2(IZITOC,izitoc,INT,STRING,A1,A2)

PROTOCCALLSFSUB6(IZOPEN,izopen,INT,STRING,STRING,STRING,INT,INT)
#define IZOPEN(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(IZOPEN,izopen,INT,STRING,STRING,STRING,INT,INT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB2(IZOUT,izout,STRING,INT)
#define IZOUT(A1,A2)  CCALLSFSUB2(IZOUT,izout,STRING,INT,A1,A2)

PROTOCCALLSFSUB2(IZPICT,izpict,PSTRING,STRING)
#define IZPICT(A1,A2)  CCALLSFSUB2(IZPICT,izpict,PSTRING,STRING,A1,A2)

PROTOCCALLSFSUB2(IZRTOC,izrtoc,FLOAT,PSTRING)
#define IZRTOC(A1,A2)  CCALLSFSUB2(IZRTOC,izrtoc,FLOAT,PSTRING,A1,A2)
