PROTOCCALLSFSUB10(HPLAER,hplaer,FLOATV,FLOATV,FLOATV,FLOATV,FLOATV,FLOATV,INT,STRING,INT,FLOAT)
#define HPLAER(A1,A2,A3,A4,A5,A6,A7,A8,A9,A10)  CCALLSFSUB10(HPLAER,hplaer,FLOATV,FLOATV,FLOATV,FLOATV,FLOATV,FLOATV,INT,STRING,INT,FLOAT,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10)

PROTOCCALLSFSUB5(HPLARC,hplarc,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT)
#define HPLARC(A1,A2,A3,A4,A5)  CCALLSFSUB5(HPLARC,hplarc,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB5(HPLBOX,hplbox,FLOAT,FLOAT,FLOAT,FLOAT,STRING)
#define HPLBOX(A1,A2,A3,A4,A5)  CCALLSFSUB5(HPLBOX,hplbox,FLOAT,FLOAT,FLOAT,FLOAT,STRING,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB1(HPLCAP,hplcap,INT)
#define HPLCAP(A1)  CCALLSFSUB1(HPLCAP,hplcap,INT,A1)

PROTOCCALLSFSUB1(HPLAX2,hplax2,FLOATV)
#define HPLAX2(A1)  CCALLSFSUB1(HPLAX2,hplax2,FLOATV,A1)

PROTOCCALLSFSUB1(HPLATT,hplatt,INT)
#define HPLATT(A1)  CCALLSFSUB1(HPLATT,hplatt,INT,A1)

PROTOCCALLSFSUB8(HPLCHA,hplcha,INT,FLOAT,FLOAT,PINT,PFLOAT,PFLOAT,PINT,PINT)
#define HPLCHA(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(HPLCHA,hplcha,INT,FLOAT,FLOAT,PINT,PFLOAT,PFLOAT,PINT,PINT,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB3(HPLCOM,hplcom,FLOAT,FLOAT,STRING)
#define HPLCOM(A1,A2,A3)  CCALLSFSUB3(HPLCOM,hplcom,FLOAT,FLOAT,STRING,A1,A2,A3)

PROTOCCALLSFSUB3(HPLABL,hplabl,INT,INT,STRINGV)
#define HPLABL(A1,A2,A3)  CCALLSFSUB3(HPLABL,hplabl,INT,INT,STRINGV,A1,A2,A3)

PROTOCCALLSFSUB3(HPLCON,hplcon,INT,INT,INT)
#define HPLCON(A1,A2,A3)  CCALLSFSUB3(HPLCON,hplcon,INT,INT,INT,A1,A2,A3)

PROTOCCALLSFSUB0(HPLDAT,hpldat)
#define HPLDAT() CCALLSFSUB0(HPLDAT,hpldat)

PROTOCCALLSFSUB1(HPLDO,hpldo,INT)
#define HPLDO(A1)  CCALLSFSUB1(HPLDO,hpldo,INT,A1)

PROTOCCALLSFSUB3(HPLEGO,hplego,INT,FLOAT,FLOAT)
#define HPLEGO(A1,A2,A3)  CCALLSFSUB3(HPLEGO,hplego,INT,FLOAT,FLOAT,A1,A2,A3)

PROTOCCALLSFSUB0(HPLEND,hplend)
#define HPLEND() CCALLSFSUB0(HPLEND,hplend)

PROTOCCALLSFSUB8(HPLERR,hplerr,FLOATV,FLOATV,FLOATV,FLOATV,INT,STRING,INT,FLOAT)
#define HPLERR(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(HPLERR,hplerr,FLOATV,FLOATV,FLOATV,FLOATV,INT,STRING,INT,FLOAT,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB9(HPLFR3,hplfr3,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,STRING)
#define HPLFR3(A1,A2,A3,A4,A5,A6,A7,A8,A9)  CCALLSFSUB9(HPLFR3,hplfr3,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,FLOAT,STRING,A1,A2,A3,A4,A5,A6,A7,A8,A9)

PROTOCCALLSFSUB5(HPLFRA,hplfra,FLOAT,FLOAT,FLOAT,FLOAT,STRING)
#define HPLFRA(A1,A2,A3,A4,A5)  CCALLSFSUB5(HPLFRA,hplfra,FLOAT,FLOAT,FLOAT,FLOAT,STRING,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB4(HPLFUN,hplfun,FLOATV,FLOATV,INT,STRING)
#define HPLFUN(A1,A2,A3,A4)  CCALLSFSUB4(HPLFUN,hplfun,FLOATV,FLOATV,INT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB4(HPLGIV,hplgiv,PFLOAT,PFLOAT,PFLOAT,PFLOAT)
#define HPLGIV(A1,A2,A3,A4)  CCALLSFSUB4(HPLGIV,hplgiv,PFLOAT,PFLOAT,PFLOAT,PFLOAT,A1,A2,A3,A4)

PROTOCCALLSFSUB0(HPLGTL,hplgtl)
#define HPLGTL() CCALLSFSUB0(HPLGTL,hplgtl)

PROTOCCALLSFSUB2(HPLGZO,hplgzo,PINT,PINT)
#define HPLGZO(A1,A2)  CCALLSFSUB2(HPLGZO,hplgzo,PINT,PINT,A1,A2)

PROTOCCALLSFSUB4(HPLINE,hpline,FLOATV,FLOATV,INT,STRING)
#define HPLINE(A1,A2,A3,A4)  CCALLSFSUB4(HPLINE,hpline,FLOATV,FLOATV,INT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB1(HPLINT,hplint,INT)
#define HPLINT(A1)  CCALLSFSUB1(HPLINT,hplint,INT,A1)

PROTOCCALLSFSUB3(HPLIST,hplist,INT,INT,INTV)
#define HPLIST(A1,A2,A3)  CCALLSFSUB3(HPLIST,hplist,INT,INT,INTV,A1,A2,A3)

PROTOCCALLSFSUB4(HPLKEY,hplkey,FLOAT,FLOAT,INT,STRING)
#define HPLKEY(A1,A2,A3,A4)  CCALLSFSUB4(HPLKEY,hplkey,FLOAT,FLOAT,INT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB0(HPLNEW,hplnew)
#define HPLNEW() CCALLSFSUB0(HPLNEW,hplnew)

PROTOCCALLSFSUB7(HPLNT,hplnt,INT,INT,FLOAT,INT,INT,INT,INT)
#define HPLNT(A1,A2,A3,A4,A5,A6,A7)  CCALLSFSUB7(HPLNT,hplnt,INT,INT,FLOAT,INT,INT,INT,INT,A1,A2,A3,A4,A5,A6,A7)

PROTOCCALLSFSUB0(HPLNUL,hplnul)
#define HPLNUL() CCALLSFSUB0(HPLNUL,hplnul)

PROTOCCALLSFSUB0(HPLNXT,hplnxt)
#define HPLNXT() CCALLSFSUB0(HPLNXT,hplnxt)

PROTOCCALLSFSUB8(HPLOC,hploc,INT,INT,PFLOAT,PFLOAT,INT,INT,INT,INT)
#define HPLOC(A1,A2,A3,A4,A5,A6,A7,A8)  CCALLSFSUB8(HPLOC,hploc,INT,INT,PFLOAT,PFLOAT,INT,INT,INT,INT,A1,A2,A3,A4,A5,A6,A7,A8)

PROTOCCALLSFSUB2(HPLOPT,hplopt,STRINGV,INT)
#define HPLOPT(A1,A2)  CCALLSFSUB2(HPLOPT,hplopt,STRINGV,INT,A1,A2)

PROTOCCALLSFSUB4(HPLOT,hplot,INT,STRING,STRING,INT)
#define HPLOT(A1,A2,A3,A4)  CCALLSFSUB4(HPLOT,hplot,INT,STRING,STRING,INT,A1,A2,A3,A4)

PROTOCCALLSFSUB3(HPLPRO,hplpro,INT,STRING,STRING)
#define HPLPRO(A1,A2,A3)  CCALLSFSUB3(HPLPRO,hplpro,INT,STRING,STRING,A1,A2,A3)

PROTOCCALLSFSUB2(HPLPTO,hplpto,STRING,PSTRING)
#define HPLPTO(A1,A2)  CCALLSFSUB2(HPLPTO,hplpto,STRING,PSTRING,A1,A2)

PROTOCCALLSFSUB2(HPLSET,hplset,STRING,PFLOAT)
#define HPLSET(A1,A2)  CCALLSFSUB2(HPLSET,hplset,STRING,PFLOAT,A1,A2)

PROTOCCALLSFSUB2(HPLQOP,hplqop,STRING,PFLOAT)
#define HPLQOP(A1,A2)  CCALLSFSUB2(HPLQOP,hplqop,STRING,PFLOAT,A1,A2)

PROTOCCALLSFSUB3(HPLSIZ,hplsiz,PFLOAT,PFLOAT,STRING)
#define HPLSIZ(A1,A2,A3)  CCALLSFSUB3(HPLSIZ,hplsiz,PFLOAT,PFLOAT,STRING,A1,A2,A3)

PROTOCCALLSFSUB7(HPLSOF,hplsof,FLOAT,FLOAT,STRING,FLOAT,FLOAT,FLOAT,INT)
#define HPLSOF(A1,A2,A3,A4,A5,A6,A7)  CCALLSFSUB7(HPLSOF,hplsof,FLOAT,FLOAT,STRING,FLOAT,FLOAT,FLOAT,INT,A1,A2,A3,A4,A5,A6,A7)

PROTOCCALLSFSUB4(HPLSUR,hplsur,INT,FLOAT,FLOAT,INT)
#define HPLSUR(A1,A2,A3,A4)  CCALLSFSUB4(HPLSUR,hplsur,INT,FLOAT,FLOAT,INT,A1,A2,A3,A4)

PROTOCCALLSFSUB6(HPLSYM,hplsym,FLOATV,FLOATV,INT,INT,FLOAT,STRING)
#define HPLSYM(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(HPLSYM,hplsym,FLOATV,FLOATV,INT,INT,FLOAT,STRING,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB4(HPLTAB,hpltab,INT,INT,FLOAT,FLOAT)
#define HPLTAB(A1,A2,A3,A4)  CCALLSFSUB4(HPLTAB,hpltab,INT,INT,FLOAT,FLOAT,A1,A2,A3,A4)

PROTOCCALLSFSUB1(HPLTIT,hpltit,STRING)
#define HPLTIT(A1)  CCALLSFSUB1(HPLTIT,hpltit,STRING,A1)

PROTOCCALLSFSUB5(HPLTOC,hpltoc,FLOAT,FLOAT,PFLOAT,PFLOAT,PINT)
#define HPLTOC(A1,A2,A3,A4,A5)  CCALLSFSUB5(HPLTOC,hpltoc,FLOAT,FLOAT,PFLOAT,PFLOAT,PINT,A1,A2,A3,A4,A5)

PROTOCCALLSFSUB6(HPLTXT,hpltxt,FLOAT,FLOAT,STRING,INT,INT,INT)
#define HPLTXT(A1,A2,A3,A4,A5,A6)  CCALLSFSUB6(HPLTXT,hpltxt,FLOAT,FLOAT,STRING,INT,INT,INT,A1,A2,A3,A4,A5,A6)

PROTOCCALLSFSUB3(HPLUSR,hplusr,INT,STRING,INT)
#define HPLUSR(A1,A2,A3)  CCALLSFSUB3(HPLUSR,hplusr,INT,STRING,INT,A1,A2,A3)

PROTOCCALLSFSUB4(HPLWIN,hplwin,INT,INT,INT,INT)
#define HPLWIN(A1,A2,A3,A4)  CCALLSFSUB4(HPLWIN,hplwin,INT,INT,INT,INT,A1,A2,A3,A4)

PROTOCCALLSFSUB4(HPLWIR,hplwir,STRING,FLOAT,FLOAT,STRING)
#define HPLWIR(A1,A2,A3,A4)  CCALLSFSUB4(HPLWIR,hplwir,STRING,FLOAT,FLOAT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB4(HPLZOM,hplzom,INT,STRING,INT,INT)
#define HPLZOM(A1,A2,A3,A4)  CCALLSFSUB4(HPLZOM,hplzom,INT,STRING,INT,INT,A1,A2,A3,A4)

PROTOCCALLSFSUB4(HPLZON,hplzon,INT,INT,INT,STRING)
#define HPLZON(A1,A2,A3,A4)  CCALLSFSUB4(HPLZON,hplzon,INT,INT,INT,STRING,A1,A2,A3,A4)

PROTOCCALLSFSUB3(HPLAXI,hplaxi,FLOATV,FLOATV,INT)
#define HPLAXI(A1,A2,A3)  CCALLSFSUB3(HPLAXI,hplaxi,FLOATV,FLOATV,INT,A1,A2,A3)

PROTOCCALLSFSUB3(HPLSTA,hplsta,INT,STRING,INT)
#define HPLSTA(A1,A2,A3) CCALLSFSUB3(HPLSTA,hplsta,INT,STRING,INT,A1,A2,A3)

PROTOCCALLSFSUB5(HPLLGD,hpllgd,STRING,STRING,STRING,INT,STRING)
#define HPLLGD(A1,A2,A3,A4,A5) CCALLSFSUB5(HPLLGD,hpllgd,STRING,STRING,STRING,INT,STRING,A1,A2,A3,A4,A5)
