PROTOCCALLSFSUB2(CZPUTA,czputa,STRING,PINT)
#define CZPUTA(CHMAIL,ISTAT) CCALLSFSUB2(CZPUTA,czputa,STRING,PINT,CHMAIL,ISTAT)

PROTOCCALLSFSUB2(CZGETA,czgeta,PSTRING,PINT)
#define CZGETA(CHMAIL,ISTAT) CCALLSFSUB2(CZGETA,czgeta,PSTRING,PINT,CHMAIL,ISTAT)
