*
* $Id: pcbuff.inc,v 1.3 1997/03/17 10:00:44 couet Exp $
*
* $Log: pcbuff.inc,v $
* Revision 1.3  1997/03/17 10:00:44  couet
* - useless lines removed
*
* Revision 1.2  1996/03/01 16:50:11  cernlib
* All includes had picked up a completely wrong #if defined(CERNLIB_UNIX), ie.
* the real commons/declarations were missing on non-unix.
*
* Revision 1.1.1.1  1996/03/01 11:38:49  mclareni
* Paw
*
*
#ifndef CERNLIB_PAW_PCBUFF_INC
#define CERNLIB_PAW_PCBUFF_INC
*
* pcbuff.inc
*
      COMMON/PCBUFF/PAWBUF(2004)
#endif
