*
* $Id: fttbug.inc,v 1.1.1.1 1996/03/07 15:17:58 mclareni Exp $
*
* $Log: fttbug.inc,v $
* Revision 1.1.1.1  1996/03/07 15:17:58  mclareni
* Fatmen
*
*
#ifndef CERNLIB_FATMEN_FTTBUG_INC
#define CERNLIB_FATMEN_FTTBUG_INC
*
*
* fttbug.inc
*
      INTEGER         IDEBFA, IDIVFA, IKDRFA, KOFSFA, KOFUFA, LBFXFA
     +              , LSAVFA, LTOPFA, LBBKFA, LBGNFA, LTDSFA, LBDSFA
     +              , LPRTFA, NTOPFA, LUFZFA, IOUPFA, IOBKFA, IODSFA
     +              , LLNLFA, LLNHFA

#endif
