/*
 * $Id: m433f2h.c,v 1.1.1.1 1996/02/15 17:47:49 mclareni Exp $
 *
 * $Log: m433f2h.c,v $
 * Revision 1.1.1.1  1996/02/15 17:47:49  mclareni
 * Kernlib
 *
 */
#include "kernbit/pilot.h"
#if defined(CERNLIB_OS9)
/*
 * Definition of the m433cs_ structure
 * generated by f2c as replacement for
 * the M433CS common in kernbit.car
 *
 * 20/09/94     Martin Merkel, CERN/CN
 */

#include "f2c.h"

struct {
        integer ichsep;
        char    chsep[1];
} m433cs_;

#endif
