*
* $Id: zstate.inc,v 1.1.1.1 1996/03/08 15:44:17 mclareni Exp $
*
* $Log: zstate.inc,v $
* Revision 1.1.1.1  1996/03/08 15:44:17  mclareni
* Cspack
*
*
#ifndef CERNLIB_CSPACK_ZSTATE_INC
#define CERNLIB_CSPACK_ZSTATE_INC
*
*               Program Status parameters
*
* zstate.inc
*
      COMMON /ZSTATE/QVERSN,NQPHAS,IQDBUG,NQDCUT,NQWCUT,NQERR
     +,              NQLOGD,NQLOGM,NQLOCK,NQDEVZ,NQAUGM(6)

#endif
