*
* $Id: pawbgn.inc,v 1.2 1996/03/01 16:49:54 cernlib Exp $
*
* $Log: pawbgn.inc,v $
* Revision 1.2  1996/03/01 16:49:54  cernlib
* All includes  had picked up a completely wrong #if defined(CERNLIB_UNIX), ie.
*  the real commons/declarations were missing on non-unix.
*
* Revision 1.1.1.1  1996/03/01 11:38:49  mclareni
* Paw
*
*
#ifndef CERNLIB_PAW_PAWBGN_INC
#define CERNLIB_PAW_PAWBGN_INC
*
*
* pawbgn.inc
*
*CMZ :  2.02/00 13/04/93  18.00.48  by  Rene Brun
*-- Author :
      COMMON/PAWBGN/ICOMIS,ISIGMA
*

#endif
