*
* $Id: pclin2.inc,v 1.2 1996/03/01 16:50:19 cernlib Exp $
*
* $Log: pclin2.inc,v $
* Revision 1.2  1996/03/01 16:50:19  cernlib
* All includes  had picked up a completely wrong #if defined(CERNLIB_UNIX), ie.
*  the real commons/declarations were missing on non-unix.
*
* Revision 1.1.1.1  1996/03/01 11:38:50  mclareni
* Paw
*
*
#ifndef CERNLIB_PAW_PCLIN2_INC
#define CERNLIB_PAW_PCLIN2_INC
*
*
* pclin2.inc
*
*CMZ :  2.02/00 13/04/93  18.00.48  by  Rene Brun
*-- Author :
      DOUBLE PRECISION AR,DEIGVA,DWORK,SS

#endif
