*
* $Id: sicsig.inc,v 1.1.1.1 1995/12/12 14:36:22 mclareni Exp $
*
* $Log: sicsig.inc,v $
* Revision 1.1.1.1  1995/12/12 14:36:22  mclareni
* Imported sources
*
*
#ifndef CERNLIB_SIGMA_SICSIG_INC
#define CERNLIB_SIGMA_SICSIG_INC
*
*
* sicsig.inc
*
*CMZ :  1.09/01 29/07/93  11.08.16  by  Carlo E. Vandoni
*-- Author :    CEV
C---  CHARACTER TYPE VARIABLES
      CHARACTER CNAME*8,CSTACK(128)*8,KOLTEX(14)*500
      COMMON/CHSIG/CNAME,CSTACK,KOLTEX

#endif
