*
* $Id: sifam4.F,v 1.1.1.1 1995/12/12 14:36:17 mclareni Exp $
*
* $Log: sifam4.F,v $
* Revision 1.1.1.1  1995/12/12 14:36:17  mclareni
* Imported sources
*
*
#include "sigma/pilot.h"
*CMZ :  1.09/04 26/10/93  09.49.18  by  Carlo E. Vandoni
*-- Author :
      SUBROUTINE SIFAM4
C    ....................................................
C         PURPOSE
C            PROCECING FAMILY 400  CODES
C
C         USAGE
C            CALL SIFAM4
C
C         COMM. BLOCKS USED
C            COM1
C
C         SUBROUTINES AND FUNCTION SUBPROGRAMS REQUIRED
C            SITRAC
C            SIDOBE
C            SIDOEN
C            SINERR
C            SIGTOX
C            SIGTOZ
C            NEXT
C            RETEND
C
C...  PAW VERSION  ...  MAY 1988
C
C    ......................................................
C
996   CALL SINERR(12)
C
 999  END
