*
* $Id: kcunit.inc,v 1.1.1.1 1996/03/08 15:32:59 mclareni Exp $
*
* $Log: kcunit.inc,v $
* Revision 1.1.1.1  1996/03/08 15:32:59  mclareni
* Kuip
*
*
#ifndef CERNLIB_KUIP_KCUNIT_INC
#define CERNLIB_KUIP_KCUNIT_INC
*
*
* kcunit.inc
*
CCCM  COMMON /KCUNIT/ ILUIN,ILUOUT,LUOUT,LUNLOG,LUNHIS,LUACT,LUNMAN
      COMMON /KCUNIT/ ILUIN,ILUOUT,LUOUT,LUNLOG,LUNHIS,LUACT,LUNMAN,
     +                LUNML
      COMMON /KCLUI/  LUIBAS,LUIFIL,LUIVR,LUIVW,
     +                LUIHIS,LUIAPP,LUIHIW,LUIMAN


#endif
