*
* $Id: hiatnm.inc,v 1.1.1.1 1996/02/14 13:10:13 mclareni Exp $
*
* $Log: hiatnm.inc,v $
* Revision 1.1.1.1  1996/02/14 13:10:13  mclareni
* Higz
*
*
#ifndef CERNLIB_HIGZ_HIATNM_INC
#define CERNLIB_HIGZ_HIATNM_INC
*
* Attributes names
*
* hiatnm.inc
*
*CMZ :  1.18/00 23/04/93  17.27.56  by  O.Couet
*-- Author :
      CHARACTER*4 CHRATT(NBRATT),CHIATT(NBIATT)
      DATA CHRATT /'MSCF','LWID','BASL','TANG','CHHE','CSHI'
     +,            'BARO','BARW','AWLN','TMSI','LASI','LAOF'/
      DATA CHIATT /'PLCI','LTYP','PMCI','MTYP','FACI','FAIS'
     +,            'FASI','TXCI','TXAL','TXFP','PASS','BORD'
     +,            'NLIN'/


#endif
