*
* $Id: hiflat.inc,v 1.1.1.1 1996/02/14 13:10:13 mclareni Exp $
*
* $Log: hiflat.inc,v $
* Revision 1.1.1.1  1996/02/14 13:10:13  mclareni
* Higz
*
*
#ifndef CERNLIB_HIGZ_HIFLAT_INC
#define CERNLIB_HIGZ_HIFLAT_INC
*
* Attributes control flags
*
* hiflat.inc
*
*CMZ :  1.18/00 23/04/93  17.27.57  by  O.Couet
*-- Author :
      COMMON /HIFLAT/
     + KMKSC,KLWSC,KBSL ,KTANG,KCHH ,KTXSH
     +,KBOF ,KBWD ,KAWL ,KTMS ,KALH ,KALD
     +,KRFLAG(18)
     +,KPLCI,KLN  ,KPMCI,KMK  ,KFACI,KFAIS
     +,KFASI,KTXCI,KTXAL,KFONT,KTXPA,KBOR
     +,KNLIN
     +,KIFLAG(17)


#endif
