*
* $Id: hiwcps.inc,v 1.1.1.1 1996/02/14 13:10:15 mclareni Exp $
*
* $Log: hiwcps.inc,v $
* Revision 1.1.1.1  1996/02/14 13:10:15  mclareni
* Higz
*
*
#ifndef CERNLIB_HIGZ_HIWCPS_INC
#define CERNLIB_HIGZ_HIWCPS_INC
*
*
* hiwcps.inc
*
*CMZ :  1.18/00 23/04/93  17.27.57  by  O.Couet
*-- Author :
      IXWCPS(U)=NINT(4.*WKMAX(IPSI)*(FX*(U-X1W)+X1V))
      IYWCPS(V)=NINT(4.*WKMAX(IPSI)*(FY*(V-Y1W)+Y1V))

#endif
